export const ADD_USER = 'ADD_USER';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const ADD_USER_LOADING = 'ADD_USER_LOADING';
export const REMOVE_USER = 'REMOVE_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';
export const SIGNUP_USER_LOADING = 'SIGNUP_USER_LOADING';